//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_setExam
    {
        public int examId { get; set; }

        [Display(Name = "Exam Date")]

        public Nullable<System.DateTime> exam_date { get; set; }

        [Display(Name = "Exam FK")]

        public Nullable<int> exam_fk_stu { get; set; }

        [Display(Name = "Exam Name")]

        public string exam_name { get; set; }

        [Display(Name = "Student Score")]

        public Nullable<int> std_score { get; set; }
            
        public virtual student student { get; set; }
    }
}
